import Head from 'next/head'
import Footer from '../components/Footer'

import styles from '../styles/Home.module.css'
import Header from '../components/Header'

export default function Gallery() {
  return (
    <div className={styles.container}>
      <Head>
        <title>See Our Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <script src="https://cdn.tailwindcss.com"></script>
     <Header></Header>
    <main className='bg-slate-100 py-40 my-20'>
        <h1 className="text-4xl">This is our awesome work</h1>
    </main>

 <Footer></Footer>
    </div>
  )
}
